{application,lodox,
             [{description,"Like Codox for LFE."},
              {vsn,"0.1.5"},
              {modules,['ld-app','ld-html-writer','ld-org-writer','ld-parse',
                        'ld-seq','ld-server','ld-sup','ld-util',
                        'unit-lodox-tests']},
              {registered,['lodox-sup']},
              {applications,[kernel,stdlib]},
              {mod,{'ld-app',[]}},
              {env,[]}]}.
